[[redirects]]
  from = "/study-library.html"
  to = "/sloanmelia-app.html"
  status = 302

[[redirects]]
  from = "/studylibrary.html"
  to = "/sloanmelia-app.html"
  status = 302

[[redirects]]
  from = "/studylibrary"
  to = "/sloanmelia-app.html"
  status = 302

[[redirects]]
  from = "/study-library"
  to = "/sloanmelia-app.html"
  status = 302

[[redirects]]
  from = "/dashboard"
  to = "/sloanmelia-app.html"
  status = 302
